### ISSUE TITLE
勉強会開催までのタスクとスケジュール

### ISSUE THREAD

**Issue by Aseiide** [Aseiide/kokurarb#1]
# スケジュール

|  タスク  |  スケジュール  |
| ---- | ---- |
|  告知  |  11/13~17 くらいに流せると良さそう  |
|  本番  |  11/27 9:30 ~ 11:30 (喋りたい人がいたら12時まで)|

# タスク

- [x] connpassかdoorkeeperか
  - [x] connpassかdoorkeeperを使うか
    - [x] connpassに決定
  - [x] どちらかでkokura.rbを作って第1回の告知を流す 
- [x] ロゴ
  - [x] 仮ロゴの作成
  - [x] ロゴを正方形にして使えるようにする
- [ ] 題材を決める
  - [ ] 第1回で扱う題材を決める
- [x] 開催概要を決める
 - [x] 当日の流れ
   - [x] 自己紹介
   - [x] 決めた題材をやる
   - [x]  アイスブレイク・雑談
 - [x] 時間
  - [x] 時間を決めてそれぞれ解く → 解法を話し合う
  - [x] 誰かの画面を共有しながら問題を解く
  - [ ] 

## 各種リンク

https://drive.google.com/drive/folders/1WhmHxL5ghtNnWeOxoT0rmC-AO6areXCZ?usp=sharing
https://gist.github.com/alt9800/a7d2588880b28671968524ba1807bab6

**Comment by alt9800** [comment]
初心者にもくもくさせる時間は長くて30分、だいたい15分くらいが妥当かな？


---実施例---
概略、などで : 1h
モブプロ : 30min
実地 :  15min
答え合わせ解説 : 15min

**Comment by alt9800** [comment]
> 概略など
- Ruby をつかうことのメリットなどを[kokura.rbのgist](https://gist.github.com/alt9800/a7d2588880b28671968524ba1807bab6)に従って説明していく
- A問題を解きつつ標準入出力の渡し方を説明
- A問題でroopやif elseでの条件分岐を学んで、
- Bでちょっとしたコーナーケースを考える [Bishop](https://atcoder.jp/contests/panasonic2020/tasks/panasonic2020_b)

**Comment by alt9800** [comment]
自分たちがファシリテートにするにせよ、参加者が聞いてるだけにならないかという懸念(もちろんそれでいい場合もあるが)

やっぱ活発な議論があったほうが嬉しい？

**Comment by Aseiide** [comment]
先に当日取り扱う問題を決める。お互い、 **A問題3個、B問題3個** ピックアップする
それをもとに、当日の流れを決める

**Comment by alt9800** [comment]
𝐼𝑑𝑒 - 𝑇𝑎𝑛𝑎𝑘𝑎 𝑆𝑒𝑙𝑒𝑐𝑡𝑖𝑜𝑛

**Comment by alt9800** [comment]
集客にエンジニアカフェ使うかな〜？

**Comment by Aseiide** [comment]
@alt9800 
> 集客にエンジニアカフェ使うかな〜？

こちらに返事できてなかった気がしている。全然エンジニアカフェのほうで集客・告知していただいて大丈夫です〜〜！

**Comment by Aseiide** [comment]
ロゴは正方形バージョンも作りました。気力があったら直すかもですが、一旦これでいこうと思います。

**Comment by Aseiide** [comment]
connpassの運営者にたなかさんを追加する、もやったほうが良さげ

**Comment by Aseiide** [comment]
次のミーティングのアジェンダ
- 問題を持ち寄って当日扱う問題を選定する
- connpassのグループ概要を書く
  - fukuoka.rbを参考にしつつ、fixしたい
  - 軽く自分が下書きしておく
- イベントページの下書き

**Comment by Aseiide** [comment]
kokura.rbの概要ページDone。
https://kokurarb.connpass.com/

**Comment by alt9800** [comment]
Connpassイベントページの下書き
https://kokurarb.connpass.com/event/229360/preview/

**Comment by Aseiide** [comment]
fukuoka.rbのCoCをフォークしてkokurarbのリポジトリにアップする

**Comment by Aseiide** [comment]
問題を解く→ディスカッションの繰り返し

**Comment by Aseiide** [comment]
取り扱う問題を決める
↓
時間配分

**Comment by Aseiide** [comment]
第一回お疲れさまでした〜。closeします
